### ISSUE TITLE
Random Order of Answers

### ISSUE THREAD

**Issue by wawimundo** [NUARIG/surveyor#123]
Hi,

I'm working on this 250-question survey. All is good except for this problem of unordered answers for some questions. See:

http://i54.tinypic.com/oqewch.png

It only happens for 2 - 3 out of the 250 questions. The weird thing is, if I regenerate the survey, the questions that have unordered answers happen randomly. Has anyone experienced this?

Dave

**Comment by yoon** [comment]
That is weird. In order to narrow this down, it would be important to see the source DSL.

Also, you could check the rails console to see if the answers have incorrectly assigned "display_order" attributes. If so, it may be a bug in the parser. If not, it could be a view issue.

Finally, these types of questions are ideas candidates for the grid type question group. Regardless, it would be good to find the source of the bug.

**Comment by kobaltz** [comment]
I have come across that issue as well. I'll see if I can find the DSL that caused it.

**Comment by yoon** [comment]
Feel free to reopen this issue if you'd like to post the code that generates these questions.
