### ISSUE TITLE
Choose a markup language for formatting question and answer text

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#285]
it would be great to choose a formatting markup language that would work with both the objective c and web versions of surveyor, so that the same formatted DSL would work for both.

**Comment by rsutphin** [comment]
I like markdown. There are lots of ruby implementations; I usually use [rdiscount](https://rubygems.org/gems/rdiscount). Quick DDGing finds several C implementations:
- [Discount](http://www.pell.portland.or.us/~orc/Code/markdown/) is what rdiscount wraps.
- [Sundown](https://github.com/tanoku/sundown) is used by GitHub and advertises the capability to do non-HTML output.

**Comment by rsutphin** [comment]
One other benefit of Markdown is that it is designed to mix its markup with plain HTML. It should be fairly safe to start applying it to existing questions (etc.), even if they are using HTML.

**Comment by hannahwhy** [comment]
Another benefit of Markdown that's pretty huge from a user perspective: Markdown text is (mostly) readable as plain text. 

I say "mostly" because some Markdown constructs like footnotes and inline images can make documents look weird, but used judiciously I don't think they affect readability too badly.

**Comment by yoon** [comment]
Consolidated into #413
