### ISSUE TITLE
Add api_ids for question groups missing api_ids

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#298]
Surveys that were imported before the api_id column was added to question_group have NULL api_ids.  We should populate the columns with NULL api_ids with type 4 UUIDs.

**Comment by yoon** [comment]
This is a good idea, but is maybe too specific to just QuestionGroup uuids. Could be extended to other models that had uuids added. Also, it might be a good idea to make it optional, such as with a rake task.

**Comment by jdzak** [comment]
I think back-populating other tables with blank UUIDs is a good idea.  

I decided to go with the migration route because they're automatic and I couldn't think of a situation where someone wouldn't want UUIDs.

**Comment by jdzak** [comment]
I'll backfill UUIDs in the other tables.

Does anyone have any opinions on whether this should be in a migration, rake task, other?

**Comment by jdzak** [comment]
I brought this up in SCRUM and @mgurley and @rsutphin preferred the migration options since it's automatic.  @yipdw had interest in both the migration and rake task option.

**Comment by rsutphin** [comment]
> ... @rsutphin preferred the migration options since it's automatic.

To expand a little, I like an automatic solution in this case because:
1. Surveyor assumes in places that there will be an `api_id` value for every record where the field is defined. It shouldn't be necessary for adopters to take special steps to insure that Surveyor's internal assumptions are true, unless they are outside our control.
2. It's safe for adopters. It only changes records that have no `api_id`. I can't see a reason why an adopter would want to force this field to be NULL.
3. It's future-proof. The migration's assumptions about the software (i.e., that there will be an `api_id` field) are guaranteed by the ordering of the migrations. It doesn't depend on anything else.
4. It's tested. We run the migrations in the CI build, so if it turns out to not be future proof, we'll find out.

Sometimes ruby-based data migrations are a bad idea, but this is not one of those situations.
