### ISSUE TITLE
Rake spec failures on Rails 3.2.3

### ISSUE THREAD

**Issue by kbighorse** [NUARIG/surveyor#302]
Followed install instructions, ran rake testbed and failed to run 'bundle exec rake spec' and got this fail:

https://gist.github.com/2388779

Trying to support Formtastic 2.x, but can't even run the current codebase tests yet. Will start with this, but if anyone knows the problem offhand, would be greatly appreciated.

Kimball

**Comment by yoon** [comment]
Looks like the issue is "Can't mass-assign protected attributes" on all of the various model attributes. Are you using attr_protected or attr_accessible anywhere? What version of Rails are you using?

**Comment by rsutphin** [comment]
I can reproduce the failures with Rails 3.2.3. They do not happen with Rails 3.2.2, 3.1.4, or 3.0.12, though the deprecation warnings are present on 3.2.2 also.

@kbighorse, if you'd like to keep working on your formtastic patch while we look into this issue, you can have your surveyor dev environment work with Rails 3.1 instead of 3.2:

```
$ export RAILS_VERSION=3.1
$ bundle update && rake testbed
$ bundle exec rake spec
```

Thanks for your interest.

**Comment by rsutphin** [comment]
[The cause](http://weblog.rubyonrails.org/2012/3/30/ann-rails-3-2-3-has-been-released/):

> This release changes the default value of config.active_record.whitelist_attributes to true. 
> This change only affects newly generated applications so it should not cause any backwards 
> compatibility issues for users who are upgrading but it may affect some tutorials and 
> introductory material.

`rake testbed` creates a new application, so `config.active_record.whitelist_attributes` will be true. Since this will be the policy in Rails going forward, we should probably add `attr_accessible` for the attributes that the surveyor controller expects to be able to set.

**Comment by kbighorse** [comment]
I'm out of the country til the 25th, I'll revisit then.  I am using Rails 3.1.4, though, so that'll be the first thing I investigate.
