### ISSUE TITLE
Store datetimes/dates/times as separate fields in the DB

### ISSUE THREAD

**Issue by jefflunt** [NUARIG/surveyor#353]
Modify surveyor's data model to include `date_value` and `time_value` in the `responses_table`, instead of storing all three of dates, times, and datetimes in a single `datetime_value` field.

The reasoning for this is that dates are dates, times are times, and datetimes are datetimes. It's been my experience that conflating them has resulted in the need for additional code to massage non-datetimes into something that fits in a datetime column, as well as the potential for subtle misinterpretations of those values when they are presented back to the user.

Details on the potential problems (in no particular order):

**Extra complexity in figuring out which interpretation is to use**

In order to figure out which of the three possible interpretations of `datetime_value` you should go with, surveyor is required to load an additional record (the associated answer record) to check the `response_class`, and then massage the data for presentation to the user.

**Subtle modifications to the meaning of questions in surveys that are invisible to users**

Storing dates as datetimes, for example, means we've got time values that are meant to be ignored, but can lead to presentation problems. 

Consider the case of a survey asking for a date of birth. If the survey needs to know the time of day as well, it could ask for a datetime. But if the survey wants to know the date only, you're not going to ask, "What day were you born, in the locality where you were born, and can you please convert that to UTC for me to make sure we're still talking about the same day."

Yet, this is the kind of subtle thing that can happen when we store dates as datetimes, and then present them back to the user. We've just created a context-sensitive interpretation of that date that shouldn't be present, and is not the intent of the question being asked.

**Addition massaging of data that isn't necessary**

In order to get dates into and out of datetime columns, we're required to do a couple of things that don't really make sense if the survey question is **actually** asking for a date. First, we append an arbitrary time to it, and second, we have to drop/ignore that time when presenting it back to the user. There are similar problems with storing times as datetimes where data is added, then read back and ignored. This could be avoided entirely if the response was stored as the intended format at the storage level.

**Surveyor hasn't always protected its data properly**

This may not be the case in the current release, but when data needs to be massaged, and especially if that massaging happens on the client side, the server can no longer be fully trusted to have the intended value for a given response when there's a mismatch between what the question as asking for, and how it's being stored. In the massaging/presentation steps there are also more moving pieces, and as such, more places the code can break.

---

I've heard that this debate goes back a long way, so please bring to light something I may be missing. One point I've heard presented so far is that  by combing the three data types into a single storage column that space is saved. However, saving space (when space is so cheap), seems like an unreasonable tradeoff when it increases the possibility of subtle bugs and misinterpretation of data captured by surveys.

**Comment by rsutphin** [comment]
Rather than further complicating the `Response` model by adding two more `_value` columns, I'd propose that we follow the simplification outlined by @yipdw in #311; i.e., store all values in a single string-serialized `value` property. 

I am not sure what the original motivation for the separate value fields _was_, but here are the potential benefits I see:
- Values may immediately be used with type-specific ruby methods/functions
- Database-level sorting, etc., using type-specific functions
- Database-level querying by values, ranges, etc.
- Database-level aggregation & statistics using type-specific functions

(Anything I missed?) AFAICT, Surveyor does not leverage any of the database-level potential benefits itself. Do any of the projects which embed it?

Separate, typed `_value` fields have several drawbacks:
- Efficient (i.e., database-level) querying/reporting is extremely complicated unless you know in advance that all response records have the same value type. To put it another way, a database-level query where you want a single "value" column across all the questions in a survey is so baroque as to be pointless.
- Surveyor & application code which merely wants to know if any value is set has to flip through all the value properties. (Cf. #310.) If said code does not flip through all the properties, bugs are introduced. (I noticed and fixed one such issue as part of #351.)
- Surveyor's code has a smell, similar to [parallel hierarchies](http://c2.com/cgi/wiki?ParallelInheritanceHierarchies), where this list of `_value` fields is duplicated across several models. I.e., it's not just in `Response`, but also in `ValidationCondition` and `DependencyCondition`.

Particularly for dates/times/datetimes, a lexicographically sortable string serialization can be arranged (ISO8601 is one for datetimes), so sorting and querying by values and ranges directly on the strings will work so long as they are all already in the same timezone.

For numeric types this is less true (selecting a lexicographically comparable string serialization would require defining a fixed range), but PostgreSQL, at least, can do type coercion in the query.

Coercion to ruby types in the Response class would be a suitable answer to the first point. While it would take some code, it would be entirely contained within a single mixin that could be applied to `Response`, `ValidationCondition` and `DependencyCondition`. With the current data model, this would require a separate hit to `Answer` in order to determine the applicable type coercion (as noted by @normalocity). If we were to store the value as a serialized string, it might be worthwhile to store a separate type field in `Response` itself indicating the type-as-provided by the user's entry so it could be appropriately coerced.

So, my counterproposal to this feature request would be to drop `datetime_value` entirely and switch to storing dates/times/datetimes as ISO8601 strings in `string_value`. In that case, the problem outlined in this
ticket would be moot, as there would be no extra data to ignore.

I also endorse a more general move to a single string `value` plus a denormalized `response_class` field on response as implied by #311, though that wouldn't necessarily need to be done at the same time.

**Comment by hannahwhy** [comment]
This is probably related more to #311 than this issue, but since we're talking about moving types around here:

If database-level sorting, querying, and aggregation are required, that's still easy to do with a type-tagged value column; there's many tools that can coerce a (type, string) pair to something else.  (Easiest way out: keep around the current `*_value` plethora, add `value`, and add an observer that contains all the coercion rules.  I think that's a waste of processing power, though, and it can be initially confusing.)

**Comment by jefflunt** [comment]
That might work, but I think we're getting at some things that maybe should be discussed as a group. There's this issue as one proposal, and there's your proposal under #311 (which I accidentally missed before Rhett pointed it out), and I see some pros and cons on both sides that if we hash it out, maybe we could just pick one way - fully native, fully serialized, or perhaps some as yet undiscussed third option.

I think you're right that having both `*_value` fields and a `value` field, as well as an observer with coercion rules would be wasteful and confusing. I think it would be better to decide on a more unified approach. With the current state of things, some values are native (e.g. integer, string, float), and some values are coerced (e.g. date, time, and datetime), so we already have a hybrid that is confusing on its own. I'd say let's not try to further that hybrid, and instead try to examine if there's a better way all around to accomplish things.

**Comment by jefflunt** [comment]
Per our discussion yesterday, the consensus is to move toward a collapsed, string-backed storage model.
