### ISSUE TITLE
Should `ResponseSets` on `Surveys` be `:dependent => :destroy` ?

### ISSUE THREAD

**Issue by jefflunt** [NUARIG/surveyor#383]
In `/lib/surveyor/models/survey_methods.rb`

Shouldn't this:

`base.send :has_many, :response_sets`

Be this:

`base.send :has_many, :response_sets, :dependent => :destroy`

Is there a reason you would retain a ResponseSet when its Survey is destroyed? All other models that are associated with "Survey" (i.e. the SurveySection, and on down the line with Questions and Answers) are `:dependent => :destroy` unless I'm missing one.

When you destroy the Survey, how would you view the ResponseSet? The Response `question_id` and `answer_id` fields would no longer point to existing records.

Is this a simple oversight, or am I missing something deeper?

**Comment by yoon** [comment]
While this is technically true, there may be situations in practice where it is not.

Other :dependent => :destroy cases: If you delete a survey, you probably intend to delete all its sections, questions, etc. If you delete a response set, you probably intend to delete its responses.

But causing someone to lose all respondent data because they didn't realize the connection between deleting a survey and all its associated response sets seems less obvious and somewhat catastrophic. While the response set data is no longer associated with a survey, questions, and answers, it is still technically usable in its isolated form.

**Comment by jefflunt** [comment]
So the ReponseSet data is still useful because, for example, you can still report on it even if the survey is gone. I guess that makes sense.

**Comment by rsutphin** [comment]
> So the ReponseSet data is still useful because, for example, you can still report on it even if the survey is gone

But only in a very limited way — I can only think of two things you would be able to recover from a ResponseSet whose Survey was deleted:
- Isolated response values (not answers). You would not be able to reliably tell _which question_ a response value was associated with, just what the value was. I can only see this being of use on very small, free-entry focused surveys.
- ResponseSet metadata — who, when, etc.

So I think you'd lose much more than you'd be able to recover. For the kinds of surveys I'm familiar with, a ResponseSet whose Survey was deleted would not be even partially useful.

So maybe what we want is to prevent deleting Surveys which have ResponseSets. If an application is really sure that it wants to purge the Survey, it's not hard for it to delete the ResponseSets first.

**Comment by yoon** [comment]
> prevent deleting Surveys which have ResponseSets

Exactly. For example, `rake surveyor:remove` only shows and deletes Surveys that don't have associated Response Sets. I think :dependent => :destroy doesn't capture the logic here.
