### ISSUE TITLE
Times showing in UTC when time zone is specified in Rails

### ISSUE THREAD

**Issue by seanvolution** [NUARIG/surveyor#435]
When the time zone is set in Rails, date times submitted in Surveyor are treated as being entered in the local time zone and are then stored in UTC.  When these times are displayed to the user, UTC is showing.  This has the affect of making the user think that their time entry has been mutated by some number of hours.

**Comment by yoon** [comment]
See comment on https://github.com/NUBIC/surveyor/pull/313#issuecomment-5518975 by @yipdw, point 3

**Comment by rsutphin** [comment]
#313 is about the API. This is talking about the UI. The UI should be obeying the configured timezone for the application.

**Comment by yoon** [comment]
"A front end displaying these timestamps will have to be adjusted to show the timezone and/or adjust for the user's timezone preference." Just noting a previous mention of this issue.

**Comment by rsutphin** [comment]
Okay, check. Just to be clear, #313 didn't actually change anything that would affect this. The problem is discussed there as though it's a potential side effect of a proposed-and-later-rejected change to the way Surveyor works. But it's actually the way Surveyor already worked when #313 was being discussed.

**Comment by yoon** [comment]
@rsutphin agreed
