### ISSUE TITLE
Add support for Rails 4.0.0rc1

### ISSUE THREAD

**Issue by kyledecot** [NUARIG/surveyor#456]
I am attempting to get your gem working w/ rails 4.0.0rc1 w/ no success. I have forked the gem and updated the line:

```
s.add_dependency('rails', '4.0.0rc1')
```

Then when attempting to do a `bundle` I get:

```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    surveyor (>= 0) ruby depends on
      actionpack (~> 3.0) ruby

    surveyor (>= 0) ruby depends on
      actionpack (4.0.0.rc1)
```

**Comment by yoon** [comment]
We haven't attempted to use surveyor with Rails 4 yet, but I believe that the versions of formtastic and rspec-rails used with surveyor are causing the actionpack dependency.

**Comment by rsutphin** [comment]
@kyledecot, thanks for giving Rails 4 support a shot. Bundler error messages are sometimes misleading, and I agree with @yoon that it is probably a transitive dependency that is causing the error you're seeing. I would also make sure to use the latest bundler, just in case there's a known bug in error reporting that's been fixed.

I don't know if this will help you with this problem, but you may want to try using the same mechanism that Surveyor uses to support testing on multiple Rails versions. Instead of adding a dependency on Rails to the gemspec, add a new clause in `Gemfile.rails_version` which makes Rails 4.0.0 selectable from the environment. E.g.:

``` ruby
  when /4.0$/
    gem 'rails', '~> 4.0.0.rc1'
    # A JS runtime is required for Rails 3.1+
    gem 'therubyracer', '~> 0.10.2'
```

(I don't know if the JS runtime is still required for Rails 4; omit it if it isn't.)

And change the gemspec like this:

```
s.add_dependency('rails', '> 3.0', '< 4.1')
```

Then you can do:

```
$ export RAILS_VERSION='4.0'
$ bundle update
$ bundle exec rake testbed
# ... and so on
```

Let us know how it goes.

**Comment by ferrisoxide** [comment]
I'm getting a little bit closer with my own efforts to port to Rails 4. The biggest issue is mass assignment in Rails 4, but slowly working through getting rspecs running. There is a work in progress here:

https://github.com/ferrisoxide/surveyor

In the rails_4 branch. Will keep people informed of progress.

**Comment by ferrisoxide** [comment]
OK.. all the rspec tests are now passing.. no idea if it actually works :) 

You'll find the code here: https://github.com/ferrisoxide/surveyor in the feature/rails_4 branch. I've had to use the protected_attributes gem, so porting this fully to Rails 4 is still a work in progress. I'll run it up in a Rails 4 app this weekend, but if anyone wants to try it out and provide feedback that'd be awesome.

**Comment by ferrisoxide** [comment]
Note rsutphin's comment about calling export RAILS_VERSION='4.0'. You will definitely need to do this prior to running the testbed.

**Comment by yoon** [comment]
The rails4 branch is working, specs are passing, and is being used in a Rails application. I'm currently refactoring the cucumber features, after which time the rails4 branch will become master.
