### ISSUE TITLE
endless survey loop

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#5]
welcome page, finishing page

**Comment by yoon** [comment]
on a per survey basis

**Comment by mgurley** [comment]
In order to stop the endless loop I modified the following files.

controllers/surveying_controller.rb
views/surveying/edit.html.haml

In the Surveying controller I modified the update action to the following(this code has redirect to url paths specific to my application):

<pre>
def update
  finished = false
  if params[:responses] or params[:response_groups]
    saved = @response_set.update_attributes(:response_attributes => (params[:responses] || {}).dup , :response_group_attributes => (params[:response_groups] || {}).dup) #copy (dup) to preserve params because we manipulate params in the response_set methods
    if (saved && params[:finish])
      @response_set.complete!
      saved = @response_set.save!
      finished = true
    end
  end
  respond_to do |format|
    format.html do
      if (finished && saved)
        flash[:notice] = "Completed survey"
        redirect_to user_path(current_user)
      else
        flash[:notice] = saved ? "" : "Unable to update survey" unless saved.nil? # Saved is nil if there are no questions on the page (ie if it only contains a label)
        redirect_to :action => "edit", :anchor => @anchor, :params => {:section => @section.id}
      end
    end
    # No redirect needed if we're talking to the page via json
    format.json do
        dependent_hash = dependents(@response_set)
        @dependents = dependent_hash[:show]
        render :json => {:show => dependent_hash[:show].map{|q| question_id_helper(q)}, :hide => dependent_hash[:hide].map{|q| question_id_helper(q)} }.to_json
    end
  end
end
</pre>

I modified  edit.html.haml to give the submit button a name of "finish" if there is not a next section like so:

<pre>
 = @section.next ? section_next_helper(@section.next) : submit_tag("Click here to finish", :name => "finish")
</pre>

**Comment by yoon** [comment]
fix for endless survey loop, allowing customizing surveyor default finish page. cleanup of extra controllers. thanks mgurley. closed by adb972ce7bbf577a08be11e31429ba7b411c4fd8
