### ISSUE TITLE
Thoughts on adding score values to responses?

### ISSUE THREAD

**Issue by hotpants** [NUARIG/surveyor#55]
I'm working on an application that will use survey-type questions to determine a municipality's eligibility for an environmental certification.

Surveyor seems quite well suited to this purpose, with one notable exception: no built-in scoring functionality.

I wonder if I could persuade one of the maintainers or really anyone interested in the subject to get me started on the "right" way to implement this in the DSL and the plugin.  I will be happy to fork and submit patches, but I'd appreciate some suggestions on how to approach this.

**Comment by hotpants** [comment]
I may have been mistaken, it seems this may be already implemented as "weight".

Looking into it now.

**Comment by yoon** [comment]
The way I see it, there would be a few ways to implement this:
1. Use the existing Surveyor Answer model - it has an integer attribute "weight".
2. Add more attributes to the Answer model, customizing the Surveyor model.
3. Add a separate model in your own application to handle the logic.

the first two can be handled in the DSL, just your weight/score add to the answer attributes hash (e.g. :weight => 2)

And you're right, there is no build-in functionality to process the scores at the end of the survey, since that's fairly application specific.
